
# Renseigner que c'est un fichier de configuration pour kubernetes
apiVersion: apps/v1
# Le type de ressource
kind: Deployment
# Metadonnées de la ressources
metadata:
  # Nom de ma ressource
  name: nginx-demo
  # Lien avec mes elements
  labels:
    app: nginx

# Specification du deployment
spec:
  # Information sur les replicats de pods
  replicas: 3
  # Lien d'appel de la ressource
  selector:
    matchLabels:
      app: nginx
  # Template = pod
  template: 
    # Métadonnées du pod
    metadata:
      labels:
        app: nginx
    # Spécification du pod
    spec: 
      containers:
      - name: nginx
        image: nginx:stable-alpine3.17
        ports:
        - containerPort: 8080
        # Limite ressource utilisation
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: mon-volume
      # ajout de mon volume
      volumes:
      - name: mon-volume
        persistentVolumeClaim:
          claimName: volume-claim-persitant

