apiVersion: v1
kind: PersistentVolume
metadata:
  name: mon-super-pv1
spec:
  # capacité de stockage du volume
  capacity:
    storage: 10Gi
  # options selon le type de stockage
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    # chemin vers le stockage cible
    path: /tmp
    # ip du serveur de stockage
    server: 172.17.0.2