apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-claim-persitant
spec:
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: slow
  volumeName: volume-claim-persitant
